# Station ID Mapping Check

Checks how well station IDs referenced in `raw_data/raw_trips` (`start_station_id`, `end_station_id`) map onto the reference station table in `raw_data/stations.parquet`.

**Important data-format note (discovered while building this notebook):** `stations.parquet` has *two* ID-like columns:
- `station_id`: a UUID-style string (e.g. `0825be94-1f3f-11e7-bf6b-3863bb334450`) — this is the GBFS station feed's canonical ID.
- `short_name`: a short numeric code as string (e.g. `"32324"`) — this matches the numeric IDs used in `raw_trips`.

`raw_trips.start_station_id` / `end_station_id` are numeric (e.g. `31208.0`) and correspond to `stations.short_name`, **not** `stations.station_id` (a direct check found 0 overlap between trip IDs and `station_id` UUIDs, vs. 817/855 overlap with `short_name`). This notebook therefore joins trip IDs against `stations.short_name`, while still surfacing `station_id` alongside results for reference.

Goals:
- Quantify exact-match coverage between trip station IDs and reference station IDs (`short_name`).
- Surface IDs that appear in trips but are missing from the station reference table (and vice versa).
- Report the row-level match rate (what share of trip rows have both endpoints resolvable to a known station ID).
- Compare ID-based coverage against the name-based coverage from [01_station_mapping_check.ipynb](01_station_mapping_check.ipynb) to see whether joining on ID resolves cases that name-matching missed.

In [1]:
from pathlib import Path

import pandas as pd

pd.set_option("display.max_rows", 100)
pd.set_option("display.max_colwidth", 100)

# Notebook lives in notebooks/, so the project root is one level up.
ROOT = Path.cwd().parent
RAW_DATA = ROOT / "raw_data"
STATIONS_PATH = RAW_DATA / "stations.parquet"
RAW_TRIPS_PATH = RAW_DATA / "raw_trips"

print(f"Project root: {ROOT}")
print(f"Stations path: {STATIONS_PATH} (exists={STATIONS_PATH.exists()})")
print(f"Raw trips path: {RAW_TRIPS_PATH} (exists={RAW_TRIPS_PATH.exists()})")

Project root: c:\Users\atlas\OneDrive\Documents\Portfolio Projects\Capital Bike Share Projects\02 Capital BikeShare Data Preprocessor
Stations path: c:\Users\atlas\OneDrive\Documents\Portfolio Projects\Capital Bike Share Projects\02 Capital BikeShare Data Preprocessor\raw_data\stations.parquet (exists=True)
Raw trips path: c:\Users\atlas\OneDrive\Documents\Portfolio Projects\Capital Bike Share Projects\02 Capital BikeShare Data Preprocessor\raw_data\raw_trips (exists=True)

## Load data

- `stations`: reference station table (`raw_data/stations.parquet`), columns include `station_id` (UUID), `short_name` (numeric/alphanumeric code — the actual trip-ID join key), `name`, `lat`, `lon`, `capacity`.
- `trips`: trip data (`raw_data/raw_trips/`), read as a full partitioned parquet dataset so any additional `year=/month=` partitions synced later are picked up automatically. Columns include `start_station_id`, `end_station_id`.

**Schema note:** `start_station_id` / `end_station_id` are stored as `int64` in older partitions (2010 through ~2020-05) but switch to a string type from 2021-02 onward, because some later station IDs are alphanumeric (e.g. `MTL-ECO5-03`, an outlier likely representing a special/placeholder station). Reading the raw partitioned dataset with pandas directly fails with `ArrowInvalid: Failed to parse string ... as a scalar of type int64` because pyarrow tries to unify all partitions under one schema inferred from the first fragment. We work around this by opening the dataset via `pyarrow.dataset` with an explicit schema that forces both ID columns to `string`, so every partition is cast consistently on read.

In [2]:
import pyarrow as pa
import pyarrow.dataset as ds

stations = pd.read_parquet(STATIONS_PATH)

# Build the trips dataset with start/end_station_id forced to string, since their
# on-disk type changes across partitions (int64 pre-2021, alphanumeric string from 2021-02 on).
_raw_dataset = ds.dataset(RAW_TRIPS_PATH, format="parquet", partitioning="hive")
_id_string_fields = []
for field in _raw_dataset.schema:
    if field.name in ("start_station_id", "end_station_id"):
        _id_string_fields.append(pa.field(field.name, pa.string()))
    else:
        _id_string_fields.append(field)
_trips_schema = pa.schema(_id_string_fields)

trips_dataset = ds.dataset(RAW_TRIPS_PATH, format="parquet", partitioning="hive", schema=_trips_schema)
trips = trips_dataset.to_table(
    columns=[
        "start_station_id",
        "end_station_id",
        "start_station_name",
        "end_station_name",
        "started_at",
        "ended_at",
        "duration",
        "period",
    ]
).to_pandas()

# Parse timestamps once, up front, for the first/last-appearance profiling done later.
trips["started_at"] = pd.to_datetime(trips["started_at"], errors="coerce")
trips["ended_at"] = pd.to_datetime(trips["ended_at"], errors="coerce")

print(f"stations: {stations.shape[0]:,} rows, columns: {list(stations.columns)}")
print(f"trips:    {trips.shape[0]:,} rows, columns: {list(trips.columns)}")
print(f"Periods covered in trips: {sorted(trips['period'].dropna().unique())}")

print("\nstations dtypes:")
print(stations.dtypes)
print("\ntrips dtypes:")
print(trips.dtypes)

stations.head()

stations: 866 rows, columns: ['station_id', 'short_name', 'name', 'lat', 'lon', 'capacity', 'updated_at']
trips:    55,897,151 rows, columns: ['start_station_id', 'end_station_id', 'start_station_name', 'end_station_name', 'started_at', 'ended_at', 'duration', 'period']
Periods covered in trips: ['2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018-01', '2018-02', '2018-03', '2018-04', '2018-05', '2018-06', '2018-07', '2018-08', '2018-09', '2018-10', '2018-11', '2018-12', '2019-01', '2019-02', '2019-03', '2019-04', '2019-05', '2019-06', '2019-07', '2019-08', '2019-09', '2019-10', '2019-11', '2019-12', '2020-01', '2020-02', '2020-03', '2020-04', '2020-05', '2020-06', '2020-07', '2020-08', '2020-09', '2020-10', '2020-11', '2020-12', '2021-01', '2021-02', '2021-03', '2021-04', '2021-05', '2021-06', '2021-07', '2021-08', '2021-09', '2021-10', '2021-11', '2021-12', '2022-01', '2022-02', '2022-03', '2022-04', '2022-05', '2022-06', '2022-07', '2022-08', '2022-09', '2022-10', '2022-11', '2022-12', '2023-01', '2023-02', '2023-03', '2023-04', '2023-05', '2023-06', '2023-07', '2023-08', '2023-09', '2023-10', '2023-11', '2023-12', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', '2025-01', '2025-02', '2025-03', '2025-04', '2025-05', '2025-06', '2025-07', '2025-08', '2025-09', '2025-10', '2025-11', '2025-12', '2026-01', '2026-02', '2026-03', '2026-04', '2026-05', '2026-06', '2026-07', '2026-08']

stations dtypes:
station_id        str
short_name        str
name              str
lat           float64
lon           float64
capacity        int64
updated_at        str
dtype: object

trips dtypes:
start_station_id                 str
end_station_id                   str
start_station_name               str
end_station_name                 str
started_at            datetime64[us]
ended_at              datetime64[us]
duration                     float64
period                           str
dtype: object

,station_id,short_name,name,lat,lon,capacity,updated_at
0,2070121870129475816,32324,Scotts Crossing Rd & Spring Gate Dr,38.927018,-77.211094,11,2026-09-26T00:50:25
1,0825be94-1f3f-11e7-bf6b-3863bb334450,31072,31st St & S Woodrow St,38.837846,-77.093478,8,2026-09-26T00:50:25
2,2254169244471500614,32367,Banneker Pool,38.922301,-77.023405,14,2026-09-26T00:50:25
3,2113890246552748136,32304,Westwood Center Dr & Sheraton Tysons Dr,38.929129,-77.246523,12,2026-09-26T00:50:25
4,082569e6-1f3f-11e7-bf6b-3863bb334450,31066,Columbia Pike & S Orme St,38.867217,-77.072296,8,2026-09-26T00:50:25

## Verify which stations column is the real join key

`trips.start_station_id` / `end_station_id` are now loaded as clean strings. `stations.station_id` is a UUID string and `stations.short_name` is a numeric/alphanumeric code string. Check overlap against both stations columns to confirm which one is the actual join key before proceeding.

In [3]:
trip_start_ids_str = trips["start_station_id"].dropna()
trip_end_ids_str = trips["end_station_id"].dropna()
trip_ids = set(trip_start_ids_str.unique()) | set(trip_end_ids_str.unique())

station_id_uuids = set(stations["station_id"].dropna().unique())
station_short_names = set(stations["short_name"].dropna().unique())

overlap_with_station_id = trip_ids & station_id_uuids
overlap_with_short_name = trip_ids & station_short_names

print(f"Unique trip station IDs (start | end):                {len(trip_ids):,}")
print(f"Overlap with stations.station_id (UUIDs):             {len(overlap_with_station_id):,}")
print(f"Overlap with stations.short_name (numeric codes):     {len(overlap_with_short_name):,}")
print(
    "\n=> Using 'stations.short_name' as the join key for trip station IDs "
    "(station_id is a UUID from a different ID space and does not correspond to trip IDs)."
)

Unique trip station IDs (start | end):                926
Overlap with stations.station_id (UUIDs):             0
Overlap with stations.short_name (numeric codes):     866

=> Using 'stations.short_name' as the join key for trip station IDs (station_id is a UUID from a different ID space and does not correspond to trip IDs).

## Build the ID universes

Define the comparison sets: reference station IDs (`stations.short_name`) vs. trip station IDs (`start_station_id` ∪ `end_station_id`). Keep `station_names` (from `stations.name`) around too, for the ID/name cross-check later.

In [4]:
station_ids = station_short_names  # reference set, already computed above
station_names = set(stations["name"].dropna().unique())  # for the ID/name cross-check later
start_ids = set(trip_start_ids_str.unique())
end_ids = set(trip_end_ids_str.unique())
# trip_ids already computed above (start_ids | end_ids)

print(f"Unique reference station IDs (stations.short_name): {len(station_ids):,}")
print(f"Unique start_station_id values:                      {len(start_ids):,}")
print(f"Unique end_station_id values:                        {len(end_ids):,}")
print(f"Unique trip station IDs (start | end):                {len(trip_ids):,}")

Unique reference station IDs (stations.short_name): 866
Unique start_station_id values:                      924
Unique end_station_id values:                        926
Unique trip station IDs (start | end):                926

## Exact-match coverage

How many trip station IDs have an exact match in the station reference table (`short_name`), and how many don't? Unlike names, IDs are exact identifiers, so there's no formatting/casing ambiguity to normalize — an ID either matches or it doesn't.

In [5]:
matched_ids = trip_ids & station_ids
trip_only_ids = trip_ids - station_ids  # in trips, missing from stations
station_only_ids = station_ids - trip_ids  # in stations, never used in trips

coverage_rate = len(matched_ids) / len(trip_ids) if trip_ids else float("nan")

print(f"Trip IDs matched exactly to a station:      {len(matched_ids):,}")
print(f"Trip IDs with NO match in stations:         {len(trip_only_ids):,}")
print(f"Station IDs never referenced in trips:      {len(station_only_ids):,}")
print(f"Exact-match coverage rate (trip IDs):       {coverage_rate:.2%}")

Trip IDs matched exactly to a station:      866
Trip IDs with NO match in stations:         60
Station IDs never referenced in trips:      0
Exact-match coverage rate (trip IDs):       93.52%

### Trip station IDs missing from the station reference table

These are `start_station_id` / `end_station_id` values that don't exactly match any `stations.short_name` value — potential data quality issues, retired/renumbered stations, or IDs from a period before the current live station feed.

In [6]:
trip_only_df = pd.DataFrame(sorted(trip_only_ids, key=lambda x: (len(x), x)), columns=["trip_station_id"])
print(f"{len(trip_only_df):,} trip station IDs have no exact match in stations.parquet (short_name)")
trip_only_df.head(50)

60 trip station IDs have no exact match in stations.parquet (short_name)

   trip_station_id
0                0
1            22907
2            31008
3            31051
4            31095
5            31200
6            31246
7            31248
8            31288
9            31329
10           31397
11           31613
12           31614
13           31642
14           31709
15           31799
16           31807
17           31823
18           31925
19           31936
20           31975
21           31980
22           32004
23           32007
24           32010
25           32013
26           32015
27           32016
28           32020
29           32030
30           32031
31           32033
32           32041
33           32042
34           32052
35           32069
36           32070
37           32071
38           32072
39           32202
40           32208
41           32217
42           32222
43           32227
44           32233
45           32239
46           32240
47           32241
48           32244
49           32245

### Reference stations never referenced in trips

Shown with `station_id` (UUID) and `name` for readability. These may be legitimate (e.g. stations added after the trip periods currently loaded) rather than data quality issues.

In [7]:
station_only_df = (
    stations.loc[stations["short_name"].isin(station_only_ids), ["short_name", "station_id", "name"]]
    .sort_values("short_name")
    .reset_index(drop=True)
)
print(f"{len(station_only_df):,} reference stations are never referenced in the loaded trip data")
station_only_df.head(50)

0 reference stations are never referenced in the loaded trip data

Empty DataFrame
Columns: [short_name, station_id, name]
Index: []

## Cross-check: do unmatched IDs correspond to unmatched names too?

IDs are opaque identifiers, so "closest match" string similarity (used for names in notebook 01) doesn't apply here. Instead, check whether trip rows with an unmatched `start_station_id`/`end_station_id` also have an unmatched `start_station_name`/`end_station_name` — if the ID is bad but the name matches fine (or vice versa), that tells us which field is more reliable for joining.

In [8]:
start_id_matched = trips["start_station_id"].isin(station_ids)
end_id_matched = trips["end_station_id"].isin(station_ids)
start_name_matched = trips["start_station_name"].isin(station_names)
end_name_matched = trips["end_station_name"].isin(station_names)

# Rows where the ID fails to match but the name matches fine, and vice versa.
start_id_bad_name_ok = (~start_id_matched) & start_name_matched
start_name_bad_id_ok = (~start_name_matched) & start_id_matched
end_id_bad_name_ok = (~end_id_matched) & end_name_matched
end_name_bad_id_ok = (~end_name_matched) & end_id_matched

print("Rows where START id is unmatched but START name IS matched: "
      f"{start_id_bad_name_ok.sum():,} ({start_id_bad_name_ok.mean():.2%})")
print("Rows where START name is unmatched but START id IS matched: "
      f"{start_name_bad_id_ok.sum():,} ({start_name_bad_id_ok.mean():.2%})")
print("Rows where END id is unmatched but END name IS matched:     "
      f"{end_id_bad_name_ok.sum():,} ({end_id_bad_name_ok.mean():.2%})")
print("Rows where END name is unmatched but END id IS matched:     "
      f"{end_name_bad_id_ok.sum():,} ({end_name_bad_id_ok.mean():.2%})")

both_id_matched = start_id_matched & end_id_matched
both_name_matched = start_name_matched & end_name_matched
print(f"\nRow-level match rate by ID (both endpoints):   {both_id_matched.mean():.2%}")
print(f"Row-level match rate by NAME (both endpoints): {both_name_matched.mean():.2%}")

Rows where START id is unmatched but START name IS matched: 28,582 (0.05%)
Rows where START name is unmatched but START id IS matched: 4,583,984 (8.20%)
Rows where END id is unmatched but END name IS matched:     38,565 (0.07%)
Rows where END name is unmatched but END id IS matched:     4,681,946 (8.38%)

Row-level match rate by ID (both endpoints):   81.33%
Row-level match rate by NAME (both endpoints): 67.77%

## Row-level match rate (by ID)

Unique-ID coverage doesn't tell us how much of the actual trip *volume* is affected. Compute, per row, whether `start_station_id` and `end_station_id` each resolve to a known station ID, and report the share of rows fully matched on both ends.

In [9]:
total_rows = len(trips)

start_id_match_rate = start_id_matched.mean()
end_id_match_rate = end_id_matched.mean()
both_id_match_rate = both_id_matched.mean()

print(f"Total trip rows:                                       {total_rows:,}")
print(f"Rows with start_station_id matched to a station:       {start_id_matched.sum():,} ({start_id_match_rate:.2%})")
print(f"Rows with end_station_id matched to a station:         {end_id_matched.sum():,} ({end_id_match_rate:.2%})")
print(f"Rows with BOTH endpoints matched (by id):              {both_id_matched.sum():,} ({both_id_match_rate:.2%})")
print(f"Rows with at least one endpoint unmatched (by id):     {(~both_id_matched).sum():,} ({(~both_id_matched).mean():.2%})")

Total trip rows:                                       55,897,151
Rows with start_station_id matched to a station:       49,509,184 (88.57%)
Rows with end_station_id matched to a station:         49,160,527 (87.95%)
Rows with BOTH endpoints matched (by id):              45,463,002 (81.33%)
Rows with at least one endpoint unmatched (by id):     10,434,149 (18.67%)

### Which unmatched IDs account for the most rows?

Ranks unmatched station IDs (start or end) by how many trip rows they appear on, so we can prioritize investigating the ones with the biggest impact. Includes the corresponding station name(s) seen in trips for that ID, for context.

In [10]:
start_id_counts = (
    trips.loc[~start_id_matched, "start_station_id"]
    .value_counts()
    .rename("as_start")
)
end_id_counts = (
    trips.loc[~end_id_matched, "end_station_id"]
    .value_counts()
    .rename("as_end")
)

unmatched_id_impact = (
    pd.concat([start_id_counts, end_id_counts], axis=1)
    .fillna(0)
    .astype(int)
)
unmatched_id_impact["total_rows"] = unmatched_id_impact["as_start"] + unmatched_id_impact["as_end"]

# Attach an example station name seen in trips for each unmatched id, for readability.
name_by_start_id = trips.loc[~start_id_matched].groupby("start_station_id")["start_station_name"].first()
name_by_end_id = trips.loc[~end_id_matched].groupby("end_station_id")["end_station_name"].first()
unmatched_id_impact["example_name"] = name_by_start_id.combine_first(name_by_end_id)

unmatched_id_impact = unmatched_id_impact.sort_values("total_rows", ascending=False)

print(f"{len(unmatched_id_impact):,} distinct unmatched IDs appear across trip rows")
print(f"They account for {unmatched_id_impact['total_rows'].sum():,} row-endpoint occurrences")
unmatched_id_impact.head(60)

60 distinct unmatched IDs appear across trip rows
They account for 4,646,030 row-endpoint occurrences

,as_start,as_end,total_rows,example_name
31200,594503,662217,1256720,Massachusetts Ave & Dupont Circle NW
31613,406826,401342,808168,Eastern Market Metro / Pennsylvania Ave & 7th St SE
31248,394161,407241,801402,Smithsonian-National Mall / Jefferson Dr & 12th St SW
31288,299978,298848,598826,4th St & Madison Dr NW
31246,252855,301950,554805,M St & Pennsylvania Ave NW
31614,92806,105521,198327,11th & H St NE
31642,76497,74722,151219,New Jersey Ave & L St NW
31008,31278,32293,63571,12th & Army Navy Dr
31051,26661,26816,53477,Arlington Blvd & N Queen St
32013,12466,9820,22286,Montgomery & East Ln
31807,8867,8587,17454,Pleasant St & MLK Ave SE
32010,5208,10161,15369,Philadelphia & Maple Ave
31936,6639,7272,13911,Fern St & Army Navy Dr
31095,6936,5193,12129,Army Navy Dr & S Nash St
31925,3849,3822,7671,Crystal Dr & Potomac Ave
32007,3554,3494,7048,E Montgomery Ave & Maryland Ave
32004,3124,3267,6391,Fallsgrove Blvd & Fallsgrove Dr
32016,2754,2649,5403,Fallsgrove Dr & W Montgomery Ave
32033,2423,2661,5084,Piccard & W Gude Dr
32217,2476,1891,4367,Sunset Hills Rd & Discovery Square
32020,2115,2169,4284,Crabbs Branch Way & Calhoun Pl
32052,1491,1460,2951,Key West Ave & Siesta Key Way
32041,1395,1356,2751,Medical Center Dr & Key West Ave
32901,696,1798,2494,6035 Warehouse
32069,1270,1179,2449,Columbus Ave & Gramercy Blvd
32071,1153,1148,2301,Corporate Blvd & Omega Dr
32222,910,837,1747,Towers Crescent Dr & Tysons One Pl
32072,906,835,1741,Key West Ave & Diamondback Dr
31329,865,873,1738,White House
32227,951,709,1660,Greensboro & Pinnacle Dr
32233,786,862,1648,Jones Branch Drive & Scotts Crossing Rd
0,776,800,1576,22nd & H St NW
32208,732,811,1543,Tysons West Transit Center
32031,703,723,1426,Taft St & E Gude Dr
32042,609,585,1194,Shady Grove Hospital
32070,580,539,1119,Key West Ave & Great Seneca Hwy
32241,578,539,1117,Reston Pkwy & Bennington Woods Rd
31823,577,528,1105,United Medical Center
32015,471,579,1050,Crabbs Branch Way & Redland Rd
32239,494,488,982,Becontree Ln & Goldenrain Ct
32256,366,398,764,North Village and Park Garden
32900,354,356,710,Motivate BX Tech office
32249,326,342,668,Green Range Dr and Glade Dr
31799,288,287,575,Randle Circle & Minnesota Ave SE
32245,274,260,534,Links Dr & Wedge Dr
32240,262,269,531,Ring Rd & North Shore Dr
32244,234,222,456,Vantage Hill Rd & Wainwright Dr
31709,220,187,407,34th St & Minnesota Ave SE
32030,211,186,397,Broschart & Blackwell Rd
31975,117,104,221,Utah St & 11th St N
32202,42,28,70,Solutions & Greensboro Dr
32351,33,30,63,Wiehle Reston Metro North
31397,29,31,60,Mission Square Dr & Miranda Ct
32902,8,21,29,Motivate Tech Office
22907,7,7,14,3035 V St
31980,4,5,9,S Wayne and 9th St
32906,0,8,8,V1 Warehouse Test Station
MTL-ECO5-03,2,2,4,MTL-ECO5-03
322840,1,2,3,Reston Cmty Ctr/Hunters Woods Plaza
32909,0,3,3,tech trailer V-1

## Profile of unmatched IDs: first/last appearance, age, and average duration

For each of the 60 unmatched IDs, compute:
- `first_appearance` / `last_appearance`: earliest/latest trip timestamp involving that ID (as either start or end)
- `age_days`: span between first and last appearance, in days
- `n_rows`: total row-endpoint occurrences (reused from `unmatched_id_impact` above)
- `avg_duration_sec`: mean trip `duration` (seconds) across all occurrences of that ID

This helps separate two different situations: a station with a long `age_days` and high `n_rows` is likely a genuine, long-lived station that's simply missing from the current live snapshot (a good candidate for a manual ID crosswalk entry); a station with a short `age_days` and very low `n_rows` is more likely a short-lived test/placeholder/decommissioned entry that's safe to leave unresolved.

In [11]:
unmatched_ids = unmatched_id_impact.index

# Occurrences of an unmatched id as a trip's start endpoint.
start_occurrences = trips.loc[
    trips["start_station_id"].isin(unmatched_ids),
    ["start_station_id", "started_at", "duration"],
].rename(columns={"start_station_id": "station_id", "started_at": "timestamp"})

# Occurrences of an unmatched id as a trip's end endpoint.
end_occurrences = trips.loc[
    trips["end_station_id"].isin(unmatched_ids),
    ["end_station_id", "ended_at", "duration"],
].rename(columns={"end_station_id": "station_id", "ended_at": "timestamp"})

occurrences = pd.concat([start_occurrences, end_occurrences], ignore_index=True)

profile = occurrences.groupby("station_id").agg(
    first_appearance=("timestamp", "min"),
    last_appearance=("timestamp", "max"),
    avg_duration_sec=("duration", "mean"),
)
profile["age_days"] = (profile["last_appearance"] - profile["first_appearance"]).dt.total_seconds() / 86400
profile["n_rows"] = unmatched_id_impact["total_rows"]
profile["example_name"] = unmatched_id_impact["example_name"]

profile = profile[
    ["example_name", "first_appearance", "last_appearance", "age_days", "n_rows", "avg_duration_sec"]
].sort_values("n_rows", ascending=False)

print(f"Profiled {len(profile):,} unmatched station IDs")
print(f"n_rows total: {profile['n_rows'].sum():,} (should match unmatched_id_impact total: {unmatched_id_impact['total_rows'].sum():,})")
profile

Profiled 60 unmatched station IDs
n_rows total: 4,646,030 (should match unmatched_id_impact total: 4,646,030)

,example_name,first_appearance,last_appearance,age_days,n_rows,avg_duration_sec
station_id,,,,,,
31200,Massachusetts Ave & Dupont Circle NW,2010-09-20 12:30:50,2025-04-01 09:46:55,5306.886169,1256720,972.745679
31613,Eastern Market Metro / Pennsylvania Ave & 7th St SE,2010-10-06 15:03:26,2024-11-19 09:24:41,5157.764757,808168,852.663755
31248,Smithsonian-National Mall / Jefferson Dr & 12th St SW,2012-04-02 08:49:01,2026-06-08 08:14:24,5179.975961,801402,2550.297562
31288,4th St & Madison Dr NW,2016-06-14 08:10:44,2026-06-05 08:27:54,3643.011921,598826,2155.167836
31246,M St & Pennsylvania Ave NW,2011-12-21 12:01:12,2025-06-11 15:44:49,4921.155289,554805,1198.906237
31614,11th & H St NE,2011-12-12 18:11:40,2021-11-30 06:55:59,3640.530775,198327,764.729241
31642,New Jersey Ave & L St NW,2016-08-02 08:42:47,2025-10-14 09:24:45,3360.029144,151219,849.399165
31008,12th & Army Navy Dr,2010-09-21 09:37:21,2019-01-03 09:23:14,3025.990197,63571,1155.617546
31051,Arlington Blvd & N Queen St,2012-09-05 07:00:42,2025-09-24 07:46:44,4767.031968,53477,999.967493
32013,Montgomery & East Ln,2013-09-27 15:48:22,2023-03-18 15:56:48,3459.005856,22286,1691.321695
31807,Pleasant St & MLK Ave SE,2013-06-04 09:14:53,2025-03-06 10:42:30,4293.060845,17454,889.008286
32010,Philadelphia & Maple Ave,2013-09-27 14:12:55,2022-10-03 17:12:01,3293.124375,15369,618.954899
31936,Fern St & Army Navy Dr,2020-11-09 10:08:29,2026-03-31 07:13:15,1967.878310,13911,NaN
31095,Army Navy Dr & S Nash St,2015-04-08 12:28:33,2026-06-25 07:51:07,4095.807338,12129,1026.558706
31925,Crystal Dr & Potomac Ave,2018-08-16 17:09:16,2021-03-08 18:15:17,935.045845,7671,876.661404
32007,E Montgomery Ave & Maryland Ave,2013-09-27 10:23:03,2024-07-10 13:20:29,3939.123218,7048,1796.144314
32004,Fallsgrove Blvd & Fallsgrove Dr,2013-09-29 11:48:35,2024-06-30 14:40:36,3927.119456,6391,1830.186428
32016,Fallsgrove Dr & W Montgomery Ave,2013-10-18 16:57:07,2024-07-01 19:59:45,3909.126829,5403,2103.601855
32033,Piccard & W Gude Dr,2013-10-27 15:28:44,2024-07-10 08:12:22,3908.696968,5084,1164.461429
32217,Sunset Hills Rd & Discovery Square,2017-01-18 16:21:23,2025-04-06 00:59:28,2999.359780,4367,896.921796
32020,Crabbs Branch Way & Calhoun Pl,2013-10-19 11:35:36,2020-06-12 17:17:53,2428.237697,4284,943.964987
32052,Key West Ave & Siesta Key Way,2016-02-20 12:53:55,2024-07-06 13:19:03,3059.017454,2951,2009.930518
32041,Medical Center Dr & Key West Ave,2014-01-09 11:54:41,2024-07-30 20:38:55,3855.364051,2751,1221.918367
32901,6035 Warehouse,2020-04-01 09:14:13,2026-07-31 08:06:55,2311.953264,2494,NaN
32069,Columbus Ave & Gramercy Blvd,2017-05-18 11:38:19,2025-04-06 22:50:39,2880.466898,2449,1604.942652
32071,Corporate Blvd & Omega Dr,2017-08-05 14:20:34,2024-06-19 09:02:16,2509.778958,2301,1827.689655
32222,Towers Crescent Dr & Tysons One Pl,2016-12-19 19:42:37,2024-06-10 21:36:27,2730.079051,1747,2071.470952
32072,Key West Ave & Diamondback Dr,2017-09-07 03:41:19,2024-06-24 13:06:42,2482.392627,1741,1965.200000
31329,White House,2021-09-07 18:02:39,2025-08-01 17:28:48,1423.976493,1738,NaN
32227,Greensboro & Pinnacle Dr,2018-05-02 16:17:54,2025-04-08 16:00:24,2532.987847,1660,1232.711679
32233,Jones Branch Drive & Scotts Crossing Rd,2019-05-16 17:44:16,2025-04-04 17:04:40,2149.972500,1648,895.442478
0,22nd & H St NW,2019-12-01 16:05:41,2020-01-21 10:54:29,50.783889,1576,759.628173
32208,Tysons West Transit Center,2016-10-21 15:42:22,2024-01-06 13:43:12,2632.917245,1543,1610.040334
32031,Taft St & E Gude Dr,2013-10-27 12:08:50,2019-11-12 11:52:40,2206.988773,1426,2548.505610
32042,Shady Grove Hospital,2014-01-09 14:51:04,2023-03-26 19:49:32,3363.207269,1194,1226.059343
32070,Key West Ave & Great Seneca Hwy,2017-05-29 10:05:07,2024-06-25 21:31:29,2584.476644,1119,1969.410405
32241,Reston Pkwy & Bennington Woods Rd,2021-07-13 18:03:46,2025-04-06 11:53:27,1362.742836,1117,NaN
31823,United Medical Center,2019-02-14 12:21:16,2025-06-07 19:37:15,2305.302766,1105,3845.372222
32015,Crabbs Branch Way & Redland Rd,2013-10-18 17:43:03,2020-06-16 19:15:39,2433.064306,1050,2108.871066
32239,Becontree Ln & Goldenrain Ct,2021-09-21 16:57:18,2025-07-30 20:36:47,1408.152419,982,NaN
32256,North Village and Park Garden,2021-09-19 17:20:25,2025-04-04 14:29:51,1292.881551,764,NaN
32900,Motivate BX Tech office,2020-04-21 07:29:40,2023-04-07 10:56:54,1081.143912,710,NaN
32249,Green Range Dr and Glade Dr,2021-07-23 19:32:25,2025-02-14 16:59:09,1301.893565,668,NaN
31799,Randle Circle & Minnesota Ave SE,2023-10-11 18:19:57,2024-08-30 21:27:18,324.130104,575,NaN
32245,Links Dr & Wedge Dr,2021-07-20 20:28:12,2024-01-08 20:44:23,902.011238,534,NaN
32240,Ring Rd & North Shore Dr,2021-07-14 07:37:06,2024-01-07 13:13:47,907.233808,531,NaN
32244,Vantage Hill Rd & Wainwright Dr,2021-07-18 19:02:56,2025-08-05 16:02:16,1478.874537,456,NaN
31709,34th St & Minnesota Ave SE,2013-06-04 11:21:02,2016-04-11 12:08:16,1042.032801,407,1308.262899
32030,Broschart & Blackwell Rd,2013-10-29 15:29:44,2020-06-09 19:57:12,2415.185741,397,1644.129630
31975,Utah St & 11th St N,2020-04-01 16:56:31,2020-04-30 19:31:22,29.107535,221,NaN
32202,Solutions & Greensboro Dr,2016-10-21 16:19:23,2017-05-20 20:42:19,211.182593,70,2304.914286
32351,Wiehle Reston Metro North,2025-09-25 18:56:52,2025-10-23 11:20:33,27.683113,63,NaN
31397,Mission Square Dr & Miranda Ct,2023-12-12 16:09:33,2024-06-10 19:57:44,181.158461,60,NaN
32902,Motivate Tech Office,2020-07-29 11:19:11,2022-09-20 11:52:19,783.023009,29,NaN
22907,3035 V St,2026-01-15 17:14:13,2026-01-15 18:27:10,0.050660,14,NaN
31980,S Wayne and 9th St,2023-10-18 14:46:45,2023-10-18 17:43:56,0.123044,9,NaN
32906,V1 Warehouse Test Station,2022-03-03 12:04:52,2022-03-03 12:04:53,0.000012,8,NaN
MTL-ECO5-03,MTL-ECO5-03,2021-02-12 17:04:26,2021-02-17 00:54:17,4.326285,4,NaN
322840,Reston Cmty Ctr/Hunters Woods Plaza,2025-02-24 11:02:19,2025-02-24 18:09:10,0.296424,3,NaN
32909,tech trailer V-1,2023-10-19 08:14:09,2024-05-29 20:05:33,223.494028,3,NaN

In [13]:
unmatched_ids = unmatched_id_impact.index

# Occurrences of an unmatched id as a trip's end endpoint.
end_occurrences = trips.loc[
    trips["end_station_id"].isin(unmatched_ids),
    ["end_station_id", "ended_at", "duration"],
].rename(columns={"end_station_id": "station_id", "ended_at": "timestamp"})

# Occurrences of an unmatched id as a trip's end endpoint.
end_occurrences = trips.loc[
    trips["end_station_id"].isin(unmatched_ids),
    ["end_station_id", "ended_at", "duration"],
].rename(columns={"end_station_id": "station_id", "ended_at": "timestamp"})

occurrences = pd.concat([end_occurrences, end_occurrences], ignore_index=True)

profile = occurrences.groupby("station_id").agg(
    first_appearance=("timestamp", "min"),
    last_appearance=("timestamp", "max"),
    avg_duration_sec=("duration", "mean"),
)
profile["age_days"] = (profile["last_appearance"] - profile["first_appearance"]).dt.total_seconds() / 86400
profile["n_rows"] = unmatched_id_impact["total_rows"]
profile["example_name"] = unmatched_id_impact["example_name"]

profile = profile[
    ["example_name", "first_appearance", "last_appearance", "age_days", "n_rows", "avg_duration_sec"]
].sort_values("n_rows", ascending=False)

print(f"Profiled {len(profile):,} unmatched station IDs")
print(f"n_rows total: {profile['n_rows'].sum():,} (should match unmatched_id_impact total: {unmatched_id_impact['total_rows'].sum():,})")
profile

Profiled 60 unmatched station IDs
n_rows total: 4,646,030 (should match unmatched_id_impact total: 4,646,030)

,example_name,first_appearance,last_appearance,age_days,n_rows,avg_duration_sec
station_id,,,,,,
31200,Massachusetts Ave & Dupont Circle NW,2010-09-20 12:30:50,2025-04-01 09:31:55,5306.875752,1256720,922.767926
31613,Eastern Market Metro / Pennsylvania Ave & 7th St SE,2010-10-06 15:03:26,2024-11-19 09:24:41,5157.764757,808168,854.077261
31248,Smithsonian-National Mall / Jefferson Dr & 12th St SW,2012-04-02 08:52:04,2026-06-08 07:58:51,5179.963044,801402,2504.658652
31288,4th St & Madison Dr NW,2016-06-14 08:47:03,2026-06-05 08:27:54,3642.986701,598826,2084.665962
31246,M St & Pennsylvania Ave NW,2011-12-21 12:02:27,2025-06-11 15:44:49,4921.154421,554805,1145.989258
31614,11th & H St NE,2011-12-12 18:11:40,2021-11-30 06:55:59,3640.530775,198327,755.979273
31642,New Jersey Ave & L St NW,2016-08-02 08:47:08,2025-10-14 09:06:45,3360.013623,151219,848.345926
31008,12th & Army Navy Dr,2010-09-21 09:38:43,2019-01-03 09:23:14,3025.989248,63571,1190.489456
31051,Arlington Blvd & N Queen St,2012-09-05 17:19:40,2025-09-23 21:59:58,4766.194653,53477,968.752036
32013,Montgomery & East Ln,2013-09-27 18:11:20,2023-03-18 15:44:03,3458.897720,22286,1470.382732
31807,Pleasant St & MLK Ave SE,2013-06-04 09:14:53,2025-03-06 10:10:21,4293.038519,17454,981.568919
32010,Philadelphia & Maple Ave,2013-09-28 11:11:45,2022-10-03 17:12:01,3292.250185,15369,505.051653
31936,Fern St & Army Navy Dr,2020-11-09 10:08:29,2026-03-30 16:14:38,1967.254271,13911,NaN
31095,Army Navy Dr & S Nash St,2015-04-08 14:19:46,2026-06-25 07:50:19,4095.729549,12129,1138.095258
31925,Crystal Dr & Potomac Ave,2018-08-16 18:12:16,2021-03-08 18:15:17,935.002095,7671,835.547014
32007,E Montgomery Ave & Maryland Ave,2013-09-27 10:24:49,2024-07-10 11:49:12,3939.058600,7048,1907.847248
32004,Fallsgrove Blvd & Fallsgrove Dr,2013-09-29 11:48:35,2024-06-30 14:10:11,3927.098333,6391,1710.528531
32016,Fallsgrove Dr & W Montgomery Ave,2013-10-19 11:18:53,2024-07-01 19:59:45,3908.361713,5403,2134.705844
32033,Piccard & W Gude Dr,2013-10-27 17:37:12,2024-07-10 08:12:22,3908.607755,5084,1095.814477
32217,Sunset Hills Rd & Discovery Square,2017-01-19 10:19:16,2025-04-06 00:59:28,2998.611250,4367,868.671930
32020,Crabbs Branch Way & Calhoun Pl,2013-10-19 11:35:36,2020-06-11 20:00:08,2427.350370,4284,892.340654
32052,Key West Ave & Siesta Key Way,2016-02-20 13:11:29,2024-07-06 13:19:03,3059.005255,2951,2083.456790
32041,Medical Center Dr & Key West Ave,2014-01-09 11:59:50,2024-07-21 19:44:36,3846.322755,2751,1248.241259
32901,6035 Warehouse,2020-04-01 09:14:13,2026-07-31 08:06:55,2311.953264,2494,NaN
32069,Columbus Ave & Gramercy Blvd,2017-05-18 11:57:37,2025-03-31 17:16:49,2874.221667,2449,1408.577670
32071,Corporate Blvd & Omega Dr,2017-08-05 14:32:57,2024-06-16 13:22:52,2506.951331,2301,1639.012844
32222,Towers Crescent Dr & Tysons One Pl,2016-12-19 20:00:19,2024-06-10 21:35:32,2730.066123,1747,1972.512397
32072,Key West Ave & Diamondback Dr,2017-09-07 03:41:19,2024-06-22 19:45:53,2480.669838,1741,2137.800000
31329,White House,2021-09-08 08:06:47,2025-08-01 08:39:25,1423.022662,1738,NaN
32227,Greensboro & Pinnacle Dr,2018-05-02 17:04:00,2025-04-07 21:39:42,2532.191458,1660,1523.565217
32233,Jones Branch Drive & Scotts Crossing Rd,2019-05-17 09:00:52,2025-03-25 08:54:01,2138.995243,1648,806.477612
0,22nd & H St NW,2019-12-01 19:06:05,2020-01-21 10:23:08,50.636840,1576,823.028750
32208,Tysons West Transit Center,2016-10-21 15:42:22,2023-12-15 20:41:52,2611.207986,1543,1617.205729
32031,Taft St & E Gude Dr,2013-10-27 13:41:36,2019-11-12 11:52:40,2206.924352,1426,2558.461964
32042,Shady Grove Hospital,2014-01-09 14:51:04,2023-03-26 19:49:32,3363.207269,1194,1096.686684
32070,Key West Ave & Great Seneca Hwy,2017-05-29 11:00:29,2024-06-25 21:31:29,2584.438194,1119,1658.282895
32241,Reston Pkwy & Bennington Woods Rd,2021-07-13 18:18:41,2025-04-04 16:40:32,1360.931840,1117,NaN
31823,United Medical Center,2019-02-14 12:41:46,2025-06-07 14:08:21,2305.060127,1105,3708.530120
32015,Crabbs Branch Way & Redland Rd,2013-10-18 17:43:03,2020-06-16 19:15:39,2433.064306,1050,1950.238532
32239,Becontree Ln & Goldenrain Ct,2021-09-21 17:27:44,2025-07-30 20:36:47,1408.131285,982,NaN
32256,North Village and Park Garden,2021-09-20 18:06:27,2025-04-04 14:28:05,1291.848356,764,NaN
32900,Motivate BX Tech office,2020-04-21 07:38:15,2023-04-07 10:56:54,1081.137951,710,NaN
32249,Green Range Dr and Glade Dr,2021-07-24 17:41:11,2025-02-10 12:51:43,1296.798981,668,NaN
31799,Randle Circle & Minnesota Ave SE,2023-10-13 15:29:42,2024-08-30 18:17:08,322.116273,575,NaN
32245,Links Dr & Wedge Dr,2021-07-20 20:28:12,2024-01-08 20:44:23,902.011238,534,NaN
32240,Ring Rd & North Shore Dr,2021-07-14 07:59:18,2024-01-07 13:12:46,907.217685,531,NaN
32244,Vantage Hill Rd & Wainwright Dr,2021-07-23 15:13:08,2025-08-05 16:02:16,1474.034120,456,NaN
31709,34th St & Minnesota Ave SE,2013-06-04 11:26:54,2016-04-11 12:08:16,1042.028727,407,1752.604278
32030,Broschart & Blackwell Rd,2013-10-29 15:29:44,2020-06-09 19:57:12,2415.185741,397,1668.534091
31975,Utah St & 11th St N,2020-04-01 18:20:06,2020-04-29 19:22:33,28.043368,221,NaN
32202,Solutions & Greensboro Dr,2016-10-21 16:19:23,2017-05-20 20:42:19,211.182593,70,615.142857
32351,Wiehle Reston Metro North,2025-09-25 18:56:52,2025-10-23 10:48:13,27.660660,63,NaN
31397,Mission Square Dr & Miranda Ct,2023-12-12 16:09:33,2024-06-10 19:57:44,181.158461,60,NaN
32902,Motivate Tech Office,2020-08-10 13:18:14,2022-09-20 11:52:19,770.940336,29,NaN
22907,3035 V St,2026-01-15 17:14:20,2026-01-15 18:27:10,0.050579,14,NaN
31980,S Wayne and 9th St,2023-10-18 14:46:45,2023-10-18 17:43:56,0.123044,9,NaN
32906,V1 Warehouse Test Station,2022-03-03 12:04:52,2022-03-03 12:04:53,0.000012,8,NaN
MTL-ECO5-03,MTL-ECO5-03,2021-02-12 17:12:10,2021-02-17 00:54:17,4.320914,4,NaN
322840,Reston Cmty Ctr/Hunters Woods Plaza,2025-02-24 11:03:33,2025-02-24 18:09:10,0.295567,3,NaN
32909,tech trailer V-1,2023-10-19 08:14:09,2024-05-29 20:05:33,223.494028,3,NaN

## Summary

In [12]:
from IPython.display import Markdown, display

summary = f"""
| Metric | Value |
|---|---|
| Reference station IDs (`stations.short_name`) | {len(station_ids):,} |
| Unique trip station IDs (start ∪ end) | {len(trip_ids):,} |
| Exact-match coverage (unique IDs) | {coverage_rate:.2%} |
| Trip IDs unmatched | {len(trip_only_ids):,} |
| Reference stations never used in trips (by id) | {len(station_only_ids):,} |
| Trip rows | {total_rows:,} |
| Row-level match rate by ID (both endpoints) | {both_id_match_rate:.2%} |
| Row-level match rate by NAME (both endpoints, for comparison) | {both_name_matched.mean():.2%} |

**Note:** `stations.station_id` (UUID) is a different ID space and was found to have 0 overlap with trip station IDs — `stations.short_name` is the correct join key. See [01_station_mapping_check.ipynb](01_station_mapping_check.ipynb) for the name-based version of this check.
"""

display(Markdown(summary))

| Metric | Value |
|---|---|
| Reference station IDs (`stations.short_name`) | 866 |
| Unique trip station IDs (start ∪ end) | 926 |
| Exact-match coverage (unique IDs) | 93.52% |
| Trip IDs unmatched | 60 |
| Reference stations never used in trips (by id) | 0 |
| Trip rows | 55,897,151 |
| Row-level match rate by ID (both endpoints) | 81.33% |
| Row-level match rate by NAME (both endpoints, for comparison) | 67.77% |

**Note:** `stations.station_id` (UUID) is a different ID space and was found to have 0 overlap with trip station IDs — `stations.short_name` is the correct join key. See [01_station_mapping_check.ipynb](01_station_mapping_check.ipynb) for the name-based version of this check.